### ISSUE TITLE
Scroll bar doesn't work in pop-up (infobox) on mobile (iPad) mode

### ISSUE THREAD

**Issue by Lounaistieto** [oskariorg/oskari-docs#124] opened 2019-08-14 12:17 UTC
Scroll bar doesn't work in pop-up (infobox) on mobile (iPad) mode. So user can see only a small part of pop-up content. Ipad Safari (6-years old, version unknown). Oskari's (karttapalvelu.lounaistieto.fi) versio 1.47.0
![IMG_0322](https://user-images.githubusercontent.com/38941232/63020202-20768e80-bea6-11e9-913a-b8c46026de62.png)
![IMG_0324](https://user-images.githubusercontent.com/38941232/63020203-20768e80-bea6-11e9-9941-28327141d6c2.png)

**Comment by ZakarFin** [comment] 2020-04-09 07:46
This probably isn't iPad related but more about infoboxes not having scrollbars and large results will stretch the popup out of the screen. As a workaround you can move the map to see the rest of the content but it's not ideal. Keeping this open for now even with no-one jumping at fixing the issue.

**Comment by ZakarFin** [comment] 2020-04-09 08:24
Just tested this on my ipad and actually the content in infobox is scrollable on my iPad using Safari and chrome on windows 10 desktop. Tested on kartta.paikkatietoikkuna,fi using Kallioperä 1:1 000 000 layer and karttapalvelu.lounaistieto.fi using LIPAS liikuntapaikat ja virkistyskohteet.

Closing as unable to reproduce. If you can give more details how to reproduce this we can continue investigating.

**Closed by ZakarFin** 2020-04-09 08:24 UTC
Labels: bug, frontend, infobox
